---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: sed
  image: hairyhenderson/sed
  commands:
  - "sed -i '/# log:log/a rrl:github.com/rancher/rrl/plugins/rrl' plugin.cfg"

- name: build
  image: golang:1.12
  commands:
  - go generate
  - rm -rf /go/pkg/mod/github.com/coreos/etcd@v3.3.11+incompatible/client/keys.generated.go
  - GO111MODULE=on CGO_ENABLED=0 go build -v -ldflags="-s -w -X github.com/rancher/coredns/coremain.GitCommit=$$(git describe --dirty --always)"

- name: docker-publish
  image: plugins/docker
  settings:
    context: .
    custom_dns: 1.1.1.1
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/coredns
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    event:
    - tag
    ref:
      include:
      - "refs/tags/*rancher*"
